### ISSUE TITLE
Support Geyser-Standalone

### ISSUE THREAD

**Issue by obtar** [kejonaMC/GeyserUpdater#105]
We using Geyser Standalone and GeyserConnect extension to proxy multiple JAVA servers.
Could it support extension for geyser extension on the Geyser-Standalone?

**Comment by onebeastchris** [comment]
Where does it say that it's a Geyser extension?

Spigot/Velocity/Bungee plugins aren't Geyser extensions, so the geyser website isn't wrongly claiming that it works on standalone.

**Comment by obtar** [comment]
You're right... sorry.
Is it will support with standalone version?

**Comment by obtar** [comment]
Re-edited the issues(⁠^⁠～⁠^⁠;⁠)⁠ゞ

**Comment by Jens-Co** [comment]
> Re-edited the issues(⁠^⁠～⁠^⁠;⁠)⁠ゞ

Hello there,

i doubt that we will make GeyserUpdater available for standalone Geyser, in order to have a system like that you need to run a seperate java app for it aswel. what i recommend is you run Geyser standalone in a docker container and each day you do a container restart and pull the latest Geyser standalone version. this way your Instance will be up to date each day.

**Comment by obtar** [comment]
Hi Jens,
You're right. 
We use a panel to host it, panel can set time to auto-restart.
When Geyser version is released, other platforms will all be updated (including standalone). 
and Geyser-standalone have plugin loader, too. Is it possible to auto-update this?

**Comment by onebeastchris** [comment]
While Geyser has a plugin loader (extensions), they can't update Geyser-Standalone itself. An extension could update other extensions, but not Geyser itself

**Comment by Jens-Co** [comment]
You definitely need to swamp/update Geyser stand-alone before it's jvm is running the application. So your best bet will be writing some script to automate this process ( build check -> pull latest version -> stop service -> remove old build and swap the new -> restart ) 

doing the update/swamp while your instance is already running (update via the plugin loader) will result in data/jar corruption.
