### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by BobtheBob123456** [kejonaMC/GeyserUpdater#82]
Hello,
I am a long time user of Geyser MC and one problem I had was every day I would have to manually update it.

Then, I found this plugin, but when I came to check it out, I couldn't find where to download. Could you please tell me where I can download the jar for this plugin?

Also, does this plugin support 1.19. 

Thanks

**Comment by Jens-Co** [comment]
Hello there, Currently the Download is not available. We still need to update our plugin, this will be fixed today. I'll let you know when we have updated it!

**Comment by Konicai** [comment]
A build should be available now. And yes, it should support 1.19
