### ISSUE TITLE
Download links on spigotmc don't point to the jars.

### ISSUE THREAD

**Issue by supersmo** [kejonaMC/GeyserUpdater#86]
The download links on spigotmc don't directly link to the jars: https://www.spigotmc.org/resources/geyserupdater.88555/history

I think this is what causes Shockbyte's convenient plugin listing to point to 1.5.0 as the latest available version of GeyserUpdater.

What it looks like when trying to install on a minecraft server using the Shockbyte plugin installation page:
![bild](https://user-images.githubusercontent.com/12717958/184512017-1300ed98-2056-4bb2-8b39-b96bac50971f.png)

**Comment by Konicai** [comment]
The download location used to point to our build server https://ci.kejona.dev/job/GeyserUpdater/job/main/ (including those versions you see in your panel)

For a temporary amount of time the download location pointed to Github Actions. I've switched it back to our build server. Try checking if more recent versions are available on shockbyte now? It might take a bit of time to update, I don't know how their system works.

**Comment by supersmo** [comment]
It's still not updated but I think it's a batch job on shockbytes end that scrapes the pages because it took about 24 hours for another plugin to update on their page. I'll check again later.

**Comment by supersmo** [comment]
Their automation has detected that there was an update Aug 13, 2022 but the selectable download hasn't picked up any newer builds. I created a support ticket with Shockbyte to see why.

I dug some more now.
As you can see from the screenshot the versions they have available are:
1.50 - Oct 02
1.4.0 - Apr 30
...
When clicking those specific entries at https://www.spigotmc.org/resources/geyserupdater.88555/history , the jar is downloaded directly, or for older ones, the download times out because the domain is dead but you can see that the target was redirected to the jar file, (Look at the date to see which exact version that was picked up)
This is not the case for any of the newer versions so my guess is that's why it doesn't work.

Not really important but is there a reason for not following semantic versioning and bumping the patch version instead of releasing the same version number multiple times?

**Comment by supersmo** [comment]
The response I got from the support ticket wasn’t very helpful:
“ Hello,

Our plugin installer is provided for convenience only, and utilizes a third party server which we do not have the power to manually update.

If a particular version or plugin you wish to use is not listed, it can be installed using the manual install section of the following guide…”

**Comment by supersmo** [comment]
I guess for their”Plugin list” page to display the newer versions, the download links need to download the jar files.

If you want to continue to persue getting your plugin to work via their convenient plugin installation page I can help with verification.

If you want to close this issue as it’s not a feature of the GeyserUpdater itself I’m OK with that too.

**Comment by Konicai** [comment]
Thanks for you effort super. I'm not against direct downloads, but when this plugin gets multiplatform support, I cannot guarantee that it will all be in one universal jar. It'll probably be in separate files like CrossplatForms. In which case it can't be a direct download. So I'm not really sure I want to change anything right now. 

I don't know what you mean by verification though

**Comment by supersmo** [comment]
By verification I just meant that if you wanted to try to get it to work I could do the testing on the shockbyte page and verify if the new versions show up there and are able to install or not.

No worries. I'll go ahead and close this issue. 😎👍
