### ISSUE TITLE
Download URL is invalid

### ISSUE THREAD

**Issue by holosand8** [kejonaMC/GeyserUpdater#92]
The command `/geyserupdate` causes following error.

```
[Sun 16:59:57 ERROR GeyserUpdater] Failed to download the newest build of Geyser
[Sun 16:59:57 WARN ] java.io.FileNotFoundException: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar
```

The download URL seems to be invalid.

* Expected: `https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/build/libs/Geyser-Spigot.jar`
* Actual: `https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar`

The exact URL can be found on the page: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastStableBuild/

**Comment by Jens-Co** [comment]
Update GeyserUpdater. 

https://ci.kejona.dev/job/GeyserUpdater/job/main/

**Comment by holosand8** [comment]
Thank you for the information. The Jenkins build binary worked well.
I had installed the latest "1.6.2" version binary from GitHub release page https://github.com/kejonaMC/GeyserUpdater/releases/tag/1.6.2 and it was NG.
The release seems to be wrong version number. Please check and fix it.

**Comment by Konicai** [comment]
I have removed the download from the GitHub release - sorry for the confusion regarding where to get the latest download.
