### ISSUE TITLE
Keeps redownloading "latest Geyser build" 

### ISSUE THREAD

**Issue by Kxsumi** [kejonaMC/GeyserUpdater#96]
![image](https://github.com/kejonaMC/GeyserUpdater/assets/96434998/1d646df3-f542-4d77-9ff8-64ad54967a32)
also this: 
![image](https://github.com/kejonaMC/GeyserUpdater/assets/96434998/36a60570-e732-4bda-b46d-e1c12b694458)

**Comment by Jens-Co** [comment]
Thanks, I recommend removing GeyserUpdater for now. I will check what's wrong later today!

**Comment by Konicai** [comment]
Fixed in b47abe2, please redownload
